# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ios-trab-final' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ios-trab-final

  target 'ios-trab-finalTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ios-trab-finalUITests' do
    # Pods for testing
  end

end
