platform :ios, '9.0'

target 'ios-trab-final' do
   # Comment the next line if you don't want to use dynamic frameworks
   use_frameworks!
 
   # Pods for ios-trab-final
 
   target 'ios-trab-finalTests' do
      inherit! :search_paths
      # Pods for testing
   end
   
   target 'ios-trab-finalUITests' do
      # Pods for testing
   end
      
   target 'cocoapods' do
      use_frameworks!

   end

   target 'AlamofireTutorial' do
      use_frameworks!
      pod 'Alamofire', '5.0.0-beta.2'
   end

end